{% set name = "functions-framework" %}
{% set version = "3.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/functions_framework-{{ version }}.tar.gz
  sha256: b699d56308a986c118773b7102cf1a8d7740557c30196f282fe509102d3aae8a

build:
  entry_points:
    - ff = functions_framework._cli:_cli
    - functions-framework = functions_framework._cli:_cli
    - functions_framework = functions_framework._cli:_cli
    - functions-framework-python = functions_framework._cli:_cli
    - functions_framework_python = functions_framework._cli:_cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [win]

requirements:
  host:
    - python
    - setuptools >=61.0.0
    - pip
  run:
    - python
    - flask >=2.0,<4.0
    - click >=7.0,<9.0
    - watchdog >=1.0.0
    - gunicorn >=22.0.0  # [unix]
    - cloudevents >=1.12.0,<=1.12.0
    - werkzeug >=0.14,<4.0.0
    - __unix  # [unix]
    - __win  # [win]
    - httpx >=0.24.1
    - starlette >=0.37.0,<1.0.0
    - uvicorn >=0.18.0,<1.0.0
    - uvicorn-worker >=0.2.0,<1.0.0
    - werkzeug >=0.14,<4.0.0

test:
  imports:
    - functions_framework
    - google
  commands:
    - pip check
    - ff --help
    - functions-framework --help
    - functions_framework --help
    - functions-framework-python --help
    - functions_framework_python --help
  requires:
    - python
    - pip

about:
  home: https://github.com/googlecloudplatform/functions-framework-python
  summary: An open source FaaS (Function as a service) framework for writing portable Python functions -- brought to you by the Google Cloud Functions team.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
